#!/usr/bin/env python3
# Copyright 2026 Mahmud
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Extract ground-truth object positions from a world SDF into a YAML file.

Every <include>/<model> named <coco_label>_<n> is reported with its label, the
centre of its visual bounding box in the *world* frame, its yaw and its size.
The robot spawn pose is stored too: slam_toolbox's map frame starts at the
robot's first odom pose, so map = inverse(spawn) * world.

Usage (from the package root, after the world has been run once so Gazebo has
cached the Fuel models, or after `gz fuel download`):
    python3 scripts/extract_ground_truth.py worlds/house.sdf \
        --models models --spawn -1.0 -2.4 0.0 --out config/ground_truth.yaml
"""

import argparse
import datetime
import os
import sys

import yaml

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
from semantic_nav_bringup.world_tools import ModelResolver, world_objects  # noqa: E402,I100


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument('world')
    parser.add_argument('--models', action='append', default=[],
                        help='directory containing local model:// models (repeatable)')
    parser.add_argument('--spawn', nargs=3, type=float, metavar=('X', 'Y', 'YAW'),
                        default=(0.0, 0.0, 0.0), help='robot spawn pose in the world frame')
    parser.add_argument('--out', required=True)
    args = parser.parse_args(argv)

    resolver = ModelResolver(model_paths=[os.path.abspath(m) for m in args.models])
    objects = list(world_objects(args.world, resolver))
    counts = {}
    for obj in objects:
        counts[obj['label']] = counts.get(obj['label'], 0) + 1

    data = {
        'world': os.path.basename(args.world),
        'generated': datetime.date.today().isoformat(),
        'frame': 'world',
        'robot_spawn': {'x': args.spawn[0], 'y': args.spawn[1], 'yaw': args.spawn[2]},
        'counts': dict(sorted(counts.items())),
        'objects': objects,
    }
    header = ('# GENERATED by scripts/extract_ground_truth.py - do not edit by hand.\n'
              '# position = centre of the visual bounding box, world frame, metres.\n'
              '# map frame = world frame re-expressed relative to robot_spawn.\n')
    with open(args.out, 'w') as f:
        f.write(header)
        yaml.safe_dump(data, f, sort_keys=False, default_flow_style=None)
    print(f'wrote {len(objects)} objects to {args.out}: {data["counts"]}')


if __name__ == '__main__':
    main()
