#!/usr/bin/env python3
# Copyright 2026 Mahmud
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Generate the meshes/textures of the two local models Fuel has no usable version of.

* models/potted_plant: tapered terracotta pot + ~30 arching leaf blades (OBJ).
* models/tv: the on-screen picture texture (PNG) for a flat-screen TV.

Deterministic (fixed RNG seed); run from the package root and commit the output:
    python3 scripts/generate_local_models.py
"""

import math
import os

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODELS = os.path.join(HERE, 'models')


# ------------------------------------------------------------------ OBJ writing
def write_obj(path, vertices, faces, double_sided=False):
    """Write vertices (N,3) and triangle faces (M,3, 0-based) with face normals."""
    faces = list(faces)
    if double_sided:  # Ogre culls back faces; thin leaves must be visible from both sides
        faces += [(a, c, b) for a, b, c in faces]
    v = np.asarray(vertices, dtype=float)
    with open(path, 'w') as f:
        f.write('# generated by scripts/generate_local_models.py\n')
        for x, y, z in v:
            f.write(f'v {x:.5f} {y:.5f} {z:.5f}\n')
        for i, (a, b, c) in enumerate(faces, start=1):
            n = np.cross(v[b] - v[a], v[c] - v[a])
            n = n / (np.linalg.norm(n) or 1.0)
            f.write(f'vn {n[0]:.4f} {n[1]:.4f} {n[2]:.4f}\n')
        for i, (a, b, c) in enumerate(faces, start=1):
            f.write(f'f {a + 1}//{i} {b + 1}//{i} {c + 1}//{i}\n')


# ------------------------------------------------------------------------ pot
def pot_mesh(r_bottom=0.13, r_top=0.17, height=0.32, rim=0.02, segments=32):
    """Tapered pot with a rim and a soil disk slightly below the top."""
    verts, faces = [], []

    def ring(radius, z):
        start = len(verts)
        for k in range(segments):
            a = 2 * math.pi * k / segments
            verts.append((radius * math.cos(a), radius * math.sin(a), z))
        return start

    def band(r0, r1):  # connect two rings (outward-facing quads)
        for k in range(segments):
            k1 = (k + 1) % segments
            faces.append((r0 + k, r0 + k1, r1 + k1))
            faces.append((r0 + k, r1 + k1, r1 + k))

    def disk(r0, z, up):
        centre = len(verts)
        verts.append((0.0, 0.0, z))
        for k in range(segments):
            k1 = (k + 1) % segments
            faces.append((centre, r0 + k, r0 + k1) if up else (centre, r0 + k1, r0 + k))

    bottom = ring(r_bottom, 0.0)
    top = ring(r_top, height - rim)
    rim_out = ring(r_top + rim, height - rim)
    rim_top = ring(r_top + rim, height)
    rim_in = ring(r_top, height)
    band(bottom, top)
    band(top, rim_out)
    band(rim_out, rim_top)
    band(rim_top, rim_in)
    disk(bottom, 0.0, up=False)
    soil = ring(r_top - 0.005, height - 0.04)
    disk(soil, height - 0.04, up=True)
    return verts, faces


# --------------------------------------------------------------------- leaves
def leaves_mesh(n_leaves=30, base_z=0.28, seed=7):
    """Arching strap-shaped leaves (think peace lily / dracaena) from the pot centre."""
    rng = np.random.default_rng(seed)
    verts, faces = [], []
    steps = 10
    for i in range(n_leaves):
        azimuth = 2 * math.pi * i / n_leaves + rng.uniform(-0.2, 0.2)
        length = rng.uniform(0.38, 0.58)
        width = rng.uniform(0.05, 0.09)
        tilt0 = rng.uniform(0.1, 0.45)          # angle from vertical at the base
        droop = rng.uniform(0.6, 1.2)            # extra bend towards the tip
        direction = np.array([math.cos(azimuth), math.sin(azimuth), 0.0])
        side = np.array([-math.sin(azimuth), math.cos(azimuth), 0.0])
        pos = np.array([0.0, 0.0, base_z]) + direction * rng.uniform(0.0, 0.04)
        start = len(verts)
        for s in range(steps + 1):
            u = s / steps
            theta = tilt0 + droop * u ** 1.6   # angle from vertical grows along the leaf
            half_w = width * 0.5 * math.sin(math.pi * min(1.0, 0.15 + u)) + 0.004
            verts.append(tuple(pos - side * half_w))
            verts.append(tuple(pos + side * half_w))
            step_dir = direction * math.sin(theta) + np.array([0, 0, 1.0]) * math.cos(theta)
            pos = pos + step_dir * (length / steps)
        for s in range(steps):
            a = start + 2 * s
            faces.append((a, a + 1, a + 3))
            faces.append((a, a + 3, a + 2))
    return verts, faces


# ------------------------------------------------------------------ TV screen
def tv_screen_texture(path, width=1024, height=576, seed=3):
    """Paint a bright landscape 'broadcast' so the TV looks switched on."""
    rng = np.random.default_rng(seed)
    img = Image.new('RGB', (width, height))
    draw = ImageDraw.Draw(img)
    horizon = int(height * 0.55)
    for y in range(horizon):  # sky gradient
        t = y / horizon
        draw.line([(0, y), (width, y)],
                  fill=(int(70 + 110 * t), int(140 + 80 * t), int(230 - 20 * t)))
    for y in range(horizon, height):  # sea gradient
        t = (y - horizon) / (height - horizon)
        draw.line([(0, y), (width, y)],
                  fill=(int(20 + 30 * t), int(120 + 60 * t), int(170 + 40 * t)))
    draw.ellipse([int(width * 0.72), 60, int(width * 0.72) + 110, 170], fill=(255, 240, 180))
    for _ in range(5):  # clouds
        cx, cy = rng.integers(50, width - 150), rng.integers(30, horizon - 120)
        for _ in range(6):
            dx, dy, r = rng.integers(-60, 60), rng.integers(-15, 15), rng.integers(25, 45)
            draw.ellipse([cx + dx - r, cy + dy - r, cx + dx + r, cy + dy + r],
                         fill=(250, 250, 252))
    island = [(int(width * 0.18), horizon + 10), (int(width * 0.32), horizon - 70),
              (int(width * 0.46), horizon - 40), (int(width * 0.58), horizon + 10)]
    draw.polygon(island, fill=(60, 130, 60))
    draw.rectangle([0, height - 40, width, height], fill=(20, 20, 30))  # news ticker bar
    draw.rectangle([20, height - 34, 180, height - 6], fill=(200, 30, 30))
    img = img.filter(ImageFilter.GaussianBlur(1.2))
    img.save(path)


def main():
    plant_dir = os.path.join(MODELS, 'potted_plant', 'meshes')
    os.makedirs(plant_dir, exist_ok=True)
    write_obj(os.path.join(plant_dir, 'pot.obj'), *pot_mesh())
    write_obj(os.path.join(plant_dir, 'leaves.obj'), *leaves_mesh(), double_sided=True)
    tv_dir = os.path.join(MODELS, 'tv', 'materials', 'textures')
    os.makedirs(tv_dir, exist_ok=True)
    tv_screen_texture(os.path.join(tv_dir, 'screen.png'))
    print('generated models in', MODELS)


if __name__ == '__main__':
    main()
